site_name: River City Rainbow Collective
docs_dir: website
site_url: https://rivercityrainbowcollective.org
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  custom_dir: website/theme_overrides/
  palette:
    scheme: rc2-theme
    primary: purple
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.tracking
extra_css:
  - assets/stylesheets/extra.css
plugins:
  - search:
  - social
  - minify:
      minify_html: true
      htmlmin_opts:
          remove_comments: true
      minify_css: true
      css_files:
        - assets/stylesheets/extra.css
        - theme_overrides/home.html

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  