site_name: River City Rainbow Collective
theme:
  name: material
  logo: assets/logo.svg
  # favicon: images/favicon.png
  custom_dir: docs/theme_overrides/
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      schem: default
      primary: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - toc.integrate
extra_css:
  - assets/stylesheets/extra.css
plugins:
  - search:
markdown_extensions:
  - attr_list
  - md_in_html
  