site_name: River City Rainbow Collective
docs_dir: website
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  custom_dir: website/theme_overrides/
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      schem: default
      primary: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    # - navigation.instant
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.tracking
extra_css:
  - assets/stylesheets/extra.css
plugins:
  - search:
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  