name: BookStack Import

on:
  # Run on schedule (daily at 6 AM UTC)
  schedule:
    - cron: '0 6 * * *'
  
  # Allow manual triggering
  workflow_dispatch:
  
  # Run on push to main branch (optional)
  push:
    branches: [ main ]
    paths:
      - 'python/**'
      - '.github/workflows/bookstack-import.yml'

jobs:
  import-bookstack:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd python
        pip install -r requirements.txt || pip install requests
        
    - name: Run BookStack import
      env:
        BOOKSTACK_BASE_URL: ${{ secrets.BOOKSTACK_BASE_URL }}
        BOOKSTACK_TOKEN_ID: ${{ secrets.BOOKSTACK_TOKEN_ID }}
        BOOKSTACK_TOKEN_SECRET: ${{ secrets.BOOKSTACK_TOKEN_SECRET }}
        BOOKSTACK_SHELF_SLUG: ${{ secrets.BOOKSTACK_SHELF_SLUG }}
      run: |
        cd python
        python scripts/import.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add website/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update website content from BookStack [skip ci]"
          git push
        fi
